version: 0.1
environment_variables:
    plaintext:
        AWS_ECR_REGISTRY: "739241322767.dkr.ecr.eu-west-1.amazonaws.com"
phases:
    pre_build:
        commands:
            - $(aws ecr get-login --region eu-west-1)
            - docker pull $AWS_ECR_REGISTRY/www-jonhewer-co-uk-build:latest
            - echo $(sed -nr 's/^\s*"version":\s*"([0-9\.]*)",$/\1/p' package.json) > VERSION
    build:
        commands:
            - docker run --volume $(pwd):/src --workdir /src $AWS_ECR_REGISTRY/www-jonhewer-co-uk-build:latest /bin/bash -c "npm install && npm run clean-build"
            - docker build -t $AWS_ECR_REGISTRY/www-jonhewer-co-uk:latest .
            - docker tag $AWS_ECR_REGISTRY/www-jonhewer-co-uk:latest $AWS_ECR_REGISTRY/www-jonhewer-co-uk:$(cat VERSION)
    post_build:
        commands:
            - docker push $AWS_ECR_REGISTRY/www-jonhewer-co-uk:latest
            - docker push $AWS_ECR_REGISTRY/www-jonhewer-co-uk:$(cat VERSION)
            - sed -i "s/VERSION/$(cat VERSION)/" cloudformation/configuration.json
artifacts:
    files:
        - cloudformation/template.yml
        - cloudformation/configuration.json
    discard-paths: yes
