version: 0.2
env:
    variables:
        AWS_ECR_REGISTRY: "739241322767.dkr.ecr.eu-west-1.amazonaws.com"
phases:
    pre_build:
        commands:
            - $(aws ecr get-login --region eu-west-1)
            - docker pull $AWS_ECR_REGISTRY/www-jonhewer-co-uk-build:latest
    build:
        commands:
            - docker run --volume $(pwd):/src --workdir /src $AWS_ECR_REGISTRY/www-jonhewer-co-uk-build:latest /bin/bash -c "npm install && npm run clean-build"
artifacts:
    files:
        - "**/*"
    base-directory: target
